// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pPMwtDeJqhjkevukr6y1tF
// Component: WiRkh1DPRNs4
import * as React from "react";

import { Link, GatsbyLinkProps as LinkProps } from "gatsby";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import LandingBannerAnimated from "../../LandingBannerAnimated"; // plasmic-import: PvD0-TnnhU/component
import { ContentfulFetcher } from "@plasmicpkgs/plasmic-contentful"; // plasmic-import: 2evg2Dug_px/codeComponent
import { ContentfulField } from "@plasmicpkgs/plasmic-contentful"; // plasmic-import: XJVyShAqlB9/codeComponent
import PostItem from "../../PostItem"; // plasmic-import: _u_Efw8ed7/component
import PostGroup from "../../PostGroup"; // plasmic-import: 7uOT7ub377V/component

import { useScreenVariants as useScreenVariantsacMvPt7MOxbgb } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: AcMvPt7MOxbgb/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "./plasmic_portfolio_revamp.module.css"; // plasmic-import: pPMwtDeJqhjkevukr6y1tF/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: WiRkh1DPRNs4/css

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {
  children?: React.ReactNode;
  children2?: React.ReactNode;
};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>(
  "children",
  "children2"
);

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  body?: p.Flex<"div">;
  siteNav?: p.Flex<"div">;
  frame21?: p.Flex<"div">;
  landingBannerAnimated?: p.Flex<typeof LandingBannerAnimated>;
  landingContent?: p.Flex<"div">;
  workPosts?: p.Flex<"div">;
  postTitleContainer2?: p.Flex<"div">;
  postTitleInnerContainer2?: p.Flex<"div">;
  projectTypeContainer3?: p.Flex<"div">;
  tagContainer?: p.Flex<"div">;
  postGroupOuterContainer?: p.Flex<"div">;
  postGroupInnerContainer?: p.Flex<"div">;
  postTitleContainer?: p.Flex<"div">;
  postTitleInnerContainer?: p.Flex<"div">;
  postNavContainer?: p.Flex<"div">;
  postItem?: p.Flex<typeof PostItem>;
  projectTypeContainer2?: p.Flex<"div">;
  blogPosts?: p.Flex<"div">;
};

export interface DefaultHomepageProps {
  children?: React.ReactNode;
  children2?: React.ReactNode;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

export function Head() {
  return <></>;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsacMvPt7MOxbgb()
  });

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"body"}
            data-plasmic-override={overrides.body}
            className={classNames(projectcss.all, sty.body)}
          >
            <div
              data-plasmic-name={"siteNav"}
              data-plasmic-override={overrides.siteNav}
              className={classNames(projectcss.all, sty.siteNav)}
            >
              {true ? (
                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__gv3VT
                  )}
                  component={Link}
                  platform={"gatsby"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2XHis
                    )}
                  >
                    {"Erik Reiblein"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__t75UL
                    )}
                  >
                    {"UX/Product Design"}
                  </div>
                </p.PlasmicLink>
              ) : null}

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame21"}
                data-plasmic-override={overrides.frame21}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame21)}
              >
                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__t1HaS
                  )}
                  component={Link}
                  platform={"gatsby"}
                >
                  {"Work"}
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__wojOi
                  )}
                  component={Link}
                  platform={"gatsby"}
                >
                  {"About"}
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__rvnpB
                  )}
                  component={Link}
                  platform={"gatsby"}
                >
                  {"Contact"}
                </p.PlasmicLink>
              </p.Stack>
            </div>

            <LandingBannerAnimated
              data-plasmic-name={"landingBannerAnimated"}
              data-plasmic-override={overrides.landingBannerAnimated}
              className={classNames(
                "__wab_instance",
                sty.landingBannerAnimated
              )}
            />

            {true ? (
              <div
                data-plasmic-name={"landingContent"}
                data-plasmic-override={overrides.landingContent}
                className={classNames(projectcss.all, sty.landingContent)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"workPosts"}
                  data-plasmic-override={overrides.workPosts}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.workPosts)}
                >
                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__uDiC)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"postTitleContainer2"}
                        data-plasmic-override={overrides.postTitleContainer2}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.postTitleContainer2
                        )}
                      >
                        <div
                          data-plasmic-name={"postTitleInnerContainer2"}
                          data-plasmic-override={
                            overrides.postTitleInnerContainer2
                          }
                          className={classNames(
                            projectcss.all,
                            sty.postTitleInnerContainer2
                          )}
                        >
                          {p.renderPlasmicSlot({
                            defaultContents: "UX Design Work",
                            value: args.children2,
                            className: classNames(sty.slotTargetChildren2)
                          })}
                        </div>
                      </p.Stack>

                      <ContentfulFetcher
                        className={classNames(
                          "__wab_instance",
                          sty.contentfulFetcher__pSyCg
                        )}
                        contentType={"blogPost" as const}
                        limit={(() => {
                          try {
                            return undefined;
                          } catch (e) {
                            if (e instanceof TypeError) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        noLayout={true}
                      >
                        <ph.DataCtxReader>
                          {$ctx => (
                            <React.Fragment>
                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__iLi40
                                )}
                                component={Link}
                                href={(() => {
                                  try {
                                    return $ctx.currentContentfulBlogPostItem
                                      .fields.slug;
                                  } catch (e) {
                                    if (e instanceof TypeError) {
                                      return `/`;
                                    }
                                    throw e;
                                  }
                                })()}
                                platform={"gatsby"}
                              >
                                <ContentfulField
                                  className={classNames(
                                    "__wab_instance",
                                    sty.contentfulField__mt4Yv
                                  )}
                                  objectPath={["postTitle"]}
                                />

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__pSbqM
                                  )}
                                >
                                  {"(For"}
                                </div>

                                <ContentfulField
                                  className={classNames(
                                    "__wab_instance",
                                    sty.contentfulField___00Vn
                                  )}
                                  objectPath={["projectClient"]}
                                />

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__lw04
                                  )}
                                >
                                  {")"}
                                </div>

                                <p.Stack
                                  as={"div"}
                                  data-plasmic-name={"projectTypeContainer3"}
                                  data-plasmic-override={
                                    overrides.projectTypeContainer3
                                  }
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.projectTypeContainer3
                                  )}
                                >
                                  <ContentfulField
                                    className={classNames(
                                      "__wab_instance",
                                      sty.contentfulField__eqOq8
                                    )}
                                    objectPath={["projectType"]}
                                  />
                                </p.Stack>
                              </p.PlasmicLink>

                              {true ? (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__yiskf
                                  )}
                                >
                                  {(
                                    (() => {
                                      try {
                                        return $ctx
                                          .currentContentfulBlogPostItem.fields
                                          .tags[0];
                                      } catch (e) {
                                        if (e instanceof TypeError) {
                                          return [];
                                        }
                                        throw e;
                                      }
                                    })() ?? []
                                  ).map((currentItem, currentIndex) => (
                                    <p.Stack
                                      as={"div"}
                                      data-plasmic-name={"tagContainer"}
                                      data-plasmic-override={
                                        overrides.tagContainer
                                      }
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.tagContainer
                                      )}
                                      key={currentIndex}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__sJ9Zh
                                        )}
                                      >
                                        {"Ideation"}
                                      </div>
                                    </p.Stack>
                                  ))}
                                </div>
                              ) : null}
                            </React.Fragment>
                          )}
                        </ph.DataCtxReader>
                      </ContentfulFetcher>
                    </div>
                  ) : null}

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"postGroupOuterContainer"}
                    data-plasmic-override={overrides.postGroupOuterContainer}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      sty.postGroupOuterContainer
                    )}
                  >
                    <div
                      data-plasmic-name={"postGroupInnerContainer"}
                      data-plasmic-override={overrides.postGroupInnerContainer}
                      className={classNames(
                        projectcss.all,
                        sty.postGroupInnerContainer
                      )}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"postTitleContainer"}
                        data-plasmic-override={overrides.postTitleContainer}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.postTitleContainer
                        )}
                      >
                        <div
                          data-plasmic-name={"postTitleInnerContainer"}
                          data-plasmic-override={
                            overrides.postTitleInnerContainer
                          }
                          className={classNames(
                            projectcss.all,
                            sty.postTitleInnerContainer
                          )}
                        >
                          {p.renderPlasmicSlot({
                            defaultContents: "UX Design Work",
                            value: args.children,
                            className: classNames(sty.slotTargetChildren)
                          })}
                        </div>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"postNavContainer"}
                        data-plasmic-override={overrides.postNavContainer}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.postNavContainer
                        )}
                      >
                        <PostItem
                          data-plasmic-name={"postItem"}
                          data-plasmic-override={overrides.postItem}
                          className={classNames("__wab_instance", sty.postItem)}
                        >
                          <ContentfulFetcher
                            className={classNames(
                              "__wab_instance",
                              sty.contentfulFetcher__yp5F
                            )}
                            contentType={"blogPost" as const}
                            entryID={"3uswRihQ79kxmUvNokovFO" as const}
                            limit={undefined}
                            noLayout={true}
                          >
                            <ph.DataCtxReader>
                              {$ctx => (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__xF52S
                                  )}
                                >
                                  <ContentfulField
                                    className={classNames(
                                      "__wab_instance",
                                      sty.contentfulField__hd1Pn
                                    )}
                                    objectPath={["postTitle"]}
                                  />

                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__gZs6B
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__jq0A0
                                      )}
                                    >
                                      {"(For"}
                                    </div>

                                    <ContentfulField
                                      className={classNames(
                                        "__wab_instance",
                                        sty.contentfulField__hr5BC
                                      )}
                                      objectPath={["projectClient"]}
                                    />

                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__albfV
                                      )}
                                    >
                                      {")"}
                                    </div>
                                  </div>

                                  <p.Stack
                                    as={"div"}
                                    data-plasmic-name={"projectTypeContainer2"}
                                    data-plasmic-override={
                                      overrides.projectTypeContainer2
                                    }
                                    hasGap={true}
                                    className={classNames(
                                      projectcss.all,
                                      sty.projectTypeContainer2
                                    )}
                                  >
                                    <ContentfulField
                                      className={classNames(
                                        "__wab_instance",
                                        sty.contentfulField__ptrwa
                                      )}
                                      objectPath={["projectType"]}
                                    />
                                  </p.Stack>
                                </div>
                              )}
                            </ph.DataCtxReader>
                          </ContentfulFetcher>
                        </PostItem>
                      </p.Stack>
                    </div>
                  </p.Stack>

                  <PostGroup
                    className={classNames(
                      "__wab_instance",
                      sty.postGroup__pdsiR
                    )}
                  >
                    {"UX Design"}
                  </PostGroup>

                  <PostGroup
                    className={classNames(
                      "__wab_instance",
                      sty.postGroup__v9FSg
                    )}
                  >
                    {"Web Design"}
                  </PostGroup>

                  <PostGroup
                    className={classNames(
                      "__wab_instance",
                      sty.postGroup__xsSxv
                    )}
                  >
                    {"Student Work"}
                  </PostGroup>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"blogPosts"}
                  data-plasmic-override={overrides.blogPosts}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.blogPosts)}
                >
                  <PostGroup
                    className={classNames(
                      "__wab_instance",
                      sty.postGroup__k9JpQ
                    )}
                  >
                    {"Blog"}
                  </PostGroup>
                </p.Stack>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "body",
    "siteNav",
    "frame21",
    "landingBannerAnimated",
    "landingContent",
    "workPosts",
    "postTitleContainer2",
    "postTitleInnerContainer2",
    "projectTypeContainer3",
    "tagContainer",
    "postGroupOuterContainer",
    "postGroupInnerContainer",
    "postTitleContainer",
    "postTitleInnerContainer",
    "postNavContainer",
    "postItem",
    "projectTypeContainer2",
    "blogPosts"
  ],
  body: [
    "body",
    "siteNav",
    "frame21",
    "landingBannerAnimated",
    "landingContent",
    "workPosts",
    "postTitleContainer2",
    "postTitleInnerContainer2",
    "projectTypeContainer3",
    "tagContainer",
    "postGroupOuterContainer",
    "postGroupInnerContainer",
    "postTitleContainer",
    "postTitleInnerContainer",
    "postNavContainer",
    "postItem",
    "projectTypeContainer2",
    "blogPosts"
  ],
  siteNav: ["siteNav", "frame21"],
  frame21: ["frame21"],
  landingBannerAnimated: ["landingBannerAnimated"],
  landingContent: [
    "landingContent",
    "workPosts",
    "postTitleContainer2",
    "postTitleInnerContainer2",
    "projectTypeContainer3",
    "tagContainer",
    "postGroupOuterContainer",
    "postGroupInnerContainer",
    "postTitleContainer",
    "postTitleInnerContainer",
    "postNavContainer",
    "postItem",
    "projectTypeContainer2",
    "blogPosts"
  ],
  workPosts: [
    "workPosts",
    "postTitleContainer2",
    "postTitleInnerContainer2",
    "projectTypeContainer3",
    "tagContainer",
    "postGroupOuterContainer",
    "postGroupInnerContainer",
    "postTitleContainer",
    "postTitleInnerContainer",
    "postNavContainer",
    "postItem",
    "projectTypeContainer2"
  ],
  postTitleContainer2: ["postTitleContainer2", "postTitleInnerContainer2"],
  postTitleInnerContainer2: ["postTitleInnerContainer2"],
  projectTypeContainer3: ["projectTypeContainer3"],
  tagContainer: ["tagContainer"],
  postGroupOuterContainer: [
    "postGroupOuterContainer",
    "postGroupInnerContainer",
    "postTitleContainer",
    "postTitleInnerContainer",
    "postNavContainer",
    "postItem",
    "projectTypeContainer2"
  ],
  postGroupInnerContainer: [
    "postGroupInnerContainer",
    "postTitleContainer",
    "postTitleInnerContainer",
    "postNavContainer",
    "postItem",
    "projectTypeContainer2"
  ],
  postTitleContainer: ["postTitleContainer", "postTitleInnerContainer"],
  postTitleInnerContainer: ["postTitleInnerContainer"],
  postNavContainer: ["postNavContainer", "postItem", "projectTypeContainer2"],
  postItem: ["postItem", "projectTypeContainer2"],
  projectTypeContainer2: ["projectTypeContainer2"],
  blogPosts: ["blogPosts"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  body: "div";
  siteNav: "div";
  frame21: "div";
  landingBannerAnimated: typeof LandingBannerAnimated;
  landingContent: "div";
  workPosts: "div";
  postTitleContainer2: "div";
  postTitleInnerContainer2: "div";
  projectTypeContainer3: "div";
  tagContainer: "div";
  postGroupOuterContainer: "div";
  postGroupInnerContainer: "div";
  postTitleContainer: "div";
  postTitleInnerContainer: "div";
  postNavContainer: "div";
  postItem: typeof PostItem;
  projectTypeContainer2: "div";
  blogPosts: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    body: makeNodeComponent("body"),
    siteNav: makeNodeComponent("siteNav"),
    frame21: makeNodeComponent("frame21"),
    landingBannerAnimated: makeNodeComponent("landingBannerAnimated"),
    landingContent: makeNodeComponent("landingContent"),
    workPosts: makeNodeComponent("workPosts"),
    postTitleContainer2: makeNodeComponent("postTitleContainer2"),
    postTitleInnerContainer2: makeNodeComponent("postTitleInnerContainer2"),
    projectTypeContainer3: makeNodeComponent("projectTypeContainer3"),
    tagContainer: makeNodeComponent("tagContainer"),
    postGroupOuterContainer: makeNodeComponent("postGroupOuterContainer"),
    postGroupInnerContainer: makeNodeComponent("postGroupInnerContainer"),
    postTitleContainer: makeNodeComponent("postTitleContainer"),
    postTitleInnerContainer: makeNodeComponent("postTitleInnerContainer"),
    postNavContainer: makeNodeComponent("postNavContainer"),
    postItem: makeNodeComponent("postItem"),
    projectTypeContainer2: makeNodeComponent("projectTypeContainer2"),
    blogPosts: makeNodeComponent("blogPosts"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
