// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pPMwtDeJqhjkevukr6y1tF
// Component: PvD0-TnnhU
import * as React from "react";

import { Link, GatsbyLinkProps as LinkProps } from "gatsby";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { Embed } from "@plasmicpkgs/plasmic-basic-components"; // plasmic-import: PKldDYkH42/codeComponent

import { useScreenVariants as useScreenVariantsacMvPt7MOxbgb } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: AcMvPt7MOxbgb/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "./plasmic_portfolio_revamp.module.css"; // plasmic-import: pPMwtDeJqhjkevukr6y1tF/projectcss
import * as sty from "./PlasmicLandingBannerAnimated.module.css"; // plasmic-import: PvD0-TnnhU/css

export type PlasmicLandingBannerAnimated__VariantMembers = {};
export type PlasmicLandingBannerAnimated__VariantsArgs = {};
type VariantPropType = keyof PlasmicLandingBannerAnimated__VariantsArgs;
export const PlasmicLandingBannerAnimated__VariantProps =
  new Array<VariantPropType>();

export type PlasmicLandingBannerAnimated__ArgsType = {};
type ArgPropType = keyof PlasmicLandingBannerAnimated__ArgsType;
export const PlasmicLandingBannerAnimated__ArgProps = new Array<ArgPropType>();

export type PlasmicLandingBannerAnimated__OverridesType = {
  pageBanner?: p.Flex<"div">;
  group17?: p.Flex<"div">;
  embedHtml?: p.Flex<typeof Embed>;
  text?: p.Flex<"div">;
};

export interface DefaultLandingBannerAnimatedProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicLandingBannerAnimated__RenderFunc(props: {
  variants: PlasmicLandingBannerAnimated__VariantsArgs;
  args: PlasmicLandingBannerAnimated__ArgsType;
  overrides: PlasmicLandingBannerAnimated__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsacMvPt7MOxbgb()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"pageBanner"}
      data-plasmic-override={overrides.pageBanner}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.pageBanner
      )}
    >
      <div
        data-plasmic-name={"group17"}
        data-plasmic-override={overrides.group17}
        className={classNames(projectcss.all, sty.group17)}
      >
        <Embed
          data-plasmic-name={"embedHtml"}
          data-plasmic-override={overrides.embedHtml}
          className={classNames("__wab_instance", sty.embedHtml)}
          code={
            '<svg viewBox="0 0 235 278" fill="none" xmlns="http://www.w3.org/2000/svg">\r\n<rect y="72.1232" width="140.224" height="226.122" rx="44.8939" transform="rotate(-24.7075 0 72.1232)" fill="#C4C0C0"/>\r\n<rect x="12.2065" y="58.9779" width="140.224" height="226.122" rx="44.8939" transform="rotate(-24.7075 12.2065 58.9779)" fill="#D9D9D9"/>\r\n<rect class="banner-ani-rect rec1" x="39.28" y="76.6851" width="106.291" height="27.5194" rx="13.7597" transform="rotate(-24.7075 39.28 76.6851)" />\r\n<rect class="banner-ani-rect rec2" x="59.8585" y="116.292" width="106.291" height="27.5194" rx="13.7597" transform="rotate(-24.7075 59.8585 116.292)"/>\r\n<rect class="banner-ani-rect rec3" x="81.4742" y="161.186" width="106.291" height="27.5194" rx="13.7597" transform="rotate(-24.7075 81.4742 161.186)"/>\r\n<rect class="banner-ani-rect rec4" x="105.584" y="206.08" width="106.291" height="27.5194" rx="13.7597" transform="rotate(-24.7075 105.584 206.08)"/>\r\n</svg>\r\n' as const
          }
        />
      </div>

      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {
          "Erik Reiblein is a user experience designer who specializes in tackling projects with complex functionality requirements."
        }
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  pageBanner: ["pageBanner", "group17", "embedHtml", "text"],
  group17: ["group17", "embedHtml"],
  embedHtml: ["embedHtml"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  pageBanner: "div";
  group17: "div";
  embedHtml: typeof Embed;
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLandingBannerAnimated__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLandingBannerAnimated__VariantsArgs;
    args?: PlasmicLandingBannerAnimated__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLandingBannerAnimated__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicLandingBannerAnimated__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLandingBannerAnimated__ArgProps,
          internalVariantPropNames: PlasmicLandingBannerAnimated__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicLandingBannerAnimated__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "pageBanner") {
    func.displayName = "PlasmicLandingBannerAnimated";
  } else {
    func.displayName = `PlasmicLandingBannerAnimated.${nodeName}`;
  }
  return func;
}

export const PlasmicLandingBannerAnimated = Object.assign(
  // Top-level PlasmicLandingBannerAnimated renders the root element
  makeNodeComponent("pageBanner"),
  {
    // Helper components rendering sub-elements
    group17: makeNodeComponent("group17"),
    embedHtml: makeNodeComponent("embedHtml"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicLandingBannerAnimated
    internalVariantProps: PlasmicLandingBannerAnimated__VariantProps,
    internalArgProps: PlasmicLandingBannerAnimated__ArgProps
  }
);

export default PlasmicLandingBannerAnimated;
/* prettier-ignore-end */
